In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns

%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import fetch_openml
hs = fetch_openml('mnist_784', version=1, as_frame=False)
hs.keys()

dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])

In [3]:
X =hs['data']
print(X.shape)
X

(70000, 784)


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [4]:
y  = hs['target']
print(y.shape)
y

(70000,)


array(['5', '0', '4', ..., '4', '5', '6'], dtype=object)

In [5]:
y = y.astype(np.uint8)

In [6]:
X_train, X_test, y_train, y_test =  X[:60000], X[60000:], y[:60000], y[60000:]

In [7]:
#Let’s try this with the SGDClassifier:

In [9]:
from sklearn.linear_model import SGDClassifier
sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train, y_train) 

SGDClassifier(random_state=42)

In [17]:
a = X_train[5]
sgd_clf.predict([a])


array([2], dtype=uint8)

In [18]:
y_train[5]

2

In [19]:
some_digit_scores = sgd_clf.decision_function([a])
some_digit_scores

array([[-15541.82888672, -29286.65271153,   3512.16981303,
         -6832.08390768, -19312.77223333,  -9222.09311121,
        -33451.06615947, -21325.87368895,  -2296.78795949,
         -6958.23332214]])

In [15]:
 np.argmax(some_digit_scores)

3

In [16]:
sgd_clf.classes_

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)